name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Basic neovim setup
        run: |
          brew install neovim
          mkdir -p $HOME/.local/share/nvim/site/pack/paqs/start/paq-nvim
          git clone --depth=1 https://github.com/savq/paq-nvim.git $HOME/.local/share/nvim/site/pack/paqs/start/paq-nvim
          mkdir -p $HOME/.config/nvim
          cp init.lua $HOME/.config/nvim
          nvim +PaqInstall +'sleep 10 | q'

      - name: Initialize repos
        run: |
          git init ./dep/1
          git init ./dep/2
          git init ./dep/3
          git init ./dep/4
          git init ./dep/5
          git init ./dep/6
          git init ./dep/7

      # Loosely based on https://egeek.me/2020/04/18/enabling-locate-on-osx/
      - name: Install glocate
        run: |
          brew install findutils
          gupdatedb --output=$HOME/locatedb --localpaths="$HOME"
          glocate -d $HOME/locatedb -r '/.git$'

      # Runs a set of commands using the runners shell
      # Run from ssh:
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
