name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v2

      - name: Basic neovim setup
        run: |
          brew install neovim
          mkdir -p $HOME/.local/share/nvim/site/pack/paqs/start/paq-nvim
          git clone --depth=1 https://github.com/savq/paq-nvim.git $HOME/.local/share/nvim/site/pack/paqs/start/paq-nvim
          mkdir -p $HOME/.config/nvim
          cp init.lua $HOME/.config/nvim

      # Runs a set of commands using the runners shell
      # Run from ssh:
      # nvim +PaqInstall
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
